# Setup
title:               BP Quantum
#tagline:             ''
description:         'B&P Technology Co., Ltd., founded in 2025, is an integrator and supplier of quantum information technology, providing customized product solutions for clients worldwide.'
url:                 https://www.bpquantum.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Wenxin Xu
  url:               
  email:             xuwenxin@shmiaofeng.cn

# 允许无日期帖子命名
permalink: /blog/:title/

collections:
  posts:
    output: true
    permalink: /:collection/:title

# 设置默认值
defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
